version: '3'

services:
  client:
    build:
      args:
        - VITE_SERVER_URL=http://zelytra.fr:8080/
    image: z-demineur-client
    ports:
      - "80:80"
    depends_on:
      - server
  server:
    image: z-demineur-server
    ports:
      - "8080:8080"

