version: '3'

services:

  client:
    image: zelytra/z-demineur-client
    container_name: z-demineur-client
    ports:
      - "9845:80"
    environment:
      VITE_SERVER_URL: ${SERVER_URL}
    depends_on:
     - server
    restart: unless-stopped

  server:
    image: zelytra/z-demineur-server
    container_name: z-demineur-server
    ports:
      - "8080:8080"
    restart: unless-stopped


